### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by KozakevichVitaliy** [KozakevichVitaliy/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by FakeAccount-bsa** [comment]
`
              <section>
                <h3>Languages</h3>
                <p class="tags small"><span class="language" lang="uk">&#x1F1FA;&#x1F1E6; УКРАЇНСЬКА </span><span
                    class="language" lang="ru">&#x1f1f7;&#x1f1fa; РУССКИЙ </span> <span class="language"
                    lang="en">&#x1f1fa;&#x1f1f8; ENGLISH: pre-intermediate</span></p>
              </section>
              
              <section>
                <h3>Skills</h3>
                <p class="tags small">HTML CSS JS PHOTOSHOP WINDOWS SQL MICROSOFT OFFICE JMETER SELENIUM WEBDRIVER JAVA
                </p>
              </section>
              
              <section>
                <h3>Character</h3>
                <p class="tags small">STRAIGHTFORWARD DEVOTED PROCRASTINATOR MELANCHOLIC CALM EMPATHETIC </p>
              </section>
              
              <section>
                <h3>Likes&#x1f603;</h3>
                <p class="tags small">SUNSET STORM ENCELADUS SPACE CATS CS50 MOUNTAINS 60S BEATNICS READING
                  CHARMOLINE-TEA SOCIAL-DRAMA RUN SCI-FI PATIENCE DEMOCRACY GRUNGE </p>
              </section>
              
              <section>
                <h3>Dislikes&#x1f61e;</h3>
                <p class="tags small"> RACISM ASS-KISSERS INCOMPETENCE ARROGANCE ENVY PREJUDICE</p>
              </section>
              
              <section>
                <h3>Wants&#x1f97a;</h3>
                <p class="tags small bulleted"><span class="tag">TO BE FIT AND HEALTHY</span><span class="tag">TO READ
                    MORE</span><span class="tag">TO LISTEN AND LEARN</span></p>
              </section>
              
              <section>
                <h3>Education</h3>
                <ul class="timeline">
                  <li>
                    <div><em>1<sup>st</sup> September 2016 &ndash; 28<sup>th</sup> February 2019</em></div>
                    <div><strong>Master's degree</strong> in <strong>Tourism</strong> at <a href="https://nuft.edu.ua/"
                        rel="external"><strong>National University of Food Techlogies</strong></a></div>
                  </li>
                  <li>
                    <div><em>1<sup>st</sup> September 2004 &ndash; 30<sup>st</sup> May 2011</em></div>
                    <div><strong>Certificate of graduation</strong> at <strong>№6 Middle School of General Education in
                        Bila Tserkva</strong></div>
                  </li>
                </ul>
              </section>
`

**Comment by FakeAccount-bsa** [comment]
`
              <section>
                <h3>Languages</h3>
                <p class="tags small"><span class="language" lang="uk">&#x1F1FA;&#x1F1E6; УКРАЇНСЬКА </span><span
                    class="language" lang="ru">&#x1f1f7;&#x1f1fa; РУССКИЙ </span> <span class="language"
                    lang="en">&#x1f1fa;&#x1f1f8; ENGLISH: pre-intermediate</span></p>
              </section>
              
              <section>
                <h3>Skills</h3>
                <p class="tags small">HTML CSS JS PHOTOSHOP WINDOWS SQL MICROSOFT OFFICE JMETER SELENIUM WEBDRIVER JAVA
                </p>
              </section>
              
              <section>
                <h3>Character</h3>
                <p class="tags small">STRAIGHTFORWARD DEVOTED PROCRASTINATOR MELANCHOLIC CALM EMPATHETIC </p>
              </section>
              
              <section>
                <h3>Likes&#x1f603;</h3>
                <p class="tags small">SUNSET STORM ENCELADUS SPACE CATS CS50 MOUNTAINS 60S BEATNICS READING
                  CHARMOLINE-TEA SOCIAL-DRAMA RUN SCI-FI PATIENCE DEMOCRACY GRUNGE </p>
              </section>
              
              <section>
                <h3>Dislikes&#x1f61e;</h3>
                <p class="tags small"> RACISM ASS-KISSERS INCOMPETENCE ARROGANCE ENVY PREJUDICE</p>
              </section>
              
              <section>
                <h3>Wants&#x1f97a;</h3>
                <p class="tags small bulleted"><span class="tag">TO BE FIT AND HEALTHY</span><span class="tag">TO READ
                    MORE</span><span class="tag">TO LISTEN AND LEARN</span></p>
              </section>
              
              <section>
                <h3>Education</h3>
                <ul class="timeline">
                  <li>
                    <div><em>1<sup>st</sup> September 2016 &ndash; 28<sup>th</sup> February 2019</em></div>
                    <div><strong>Master's degree</strong> in <strong>Tourism</strong> at <a href="https://nuft.edu.ua/"
                        rel="external"><strong>National University of Food Techlogies</strong></a></div>
                  </li>
                  <li>
                    <div><em>1<sup>st</sup> September 2004 &ndash; 30<sup>st</sup> May 2011</em></div>
                    <div><strong>Certificate of graduation</strong> at <strong>№6 Middle School of General Education in
                        Bila Tserkva</strong></div>
                  </li>
                </ul>
              </section>
`

**Comment by FakeAccount-bsa** [comment]
`
<div class="six wide column">
              
              <section>
                <h3>Languages</h3>
                <p class="tags small"><span class="language" lang="uk">&#x1F1FA;&#x1F1E6; УКРАЇНСЬКА </span><span
                    class="language" lang="ru">&#x1f1f7;&#x1f1fa; РУССКИЙ </span> <span class="language"
                    lang="en">&#x1f1fa;&#x1f1f8; ENGLISH: pre-intermediate</span></p>
              </section>
              
              <section>
                <h3>Skills</h3>
                <p class="tags small">HTML CSS JS PHOTOSHOP WINDOWS SQL MICROSOFT OFFICE JMETER SELENIUM WEBDRIVER JAVA
                </p>
              </section>
              
              <section>
                <h3>Character</h3>
                <p class="tags small">STRAIGHTFORWARD DEVOTED PROCRASTINATOR MELANCHOLIC CALM EMPATHETIC </p>
              </section>
              
              <section>
                <h3>Likes&#x1f603;</h3>
                <p class="tags small">SUNSET STORM ENCELADUS SPACE CATS CS50 MOUNTAINS 60S BEATNICS READING
                  CHARMOLINE-TEA SOCIAL-DRAMA RUN SCI-FI PATIENCE DEMOCRACY GRUNGE </p>
              </section>
              
              <section>
                <h3>Dislikes&#x1f61e;</h3>
                <p class="tags small"> RACISM ASS-KISSERS INCOMPETENCE ARROGANCE ENVY PREJUDICE</p>
              </section>
              
              <section>
                <h3>Wants&#x1f97a;</h3>
                <p class="tags small bulleted"><span class="tag">TO BE FIT AND HEALTHY</span><span class="tag">TO READ
                    MORE</span><span class="tag">TO LISTEN AND LEARN</span></p>
              </section>
              
              <section>
                <h3>Education</h3>
                <ul class="timeline">
                  <li>
                    <div><em>1<sup>st</sup> September 2016 &ndash; 28<sup>th</sup> February 2019</em></div>
                    <div><strong>Master's degree</strong> in <strong>Tourism</strong> at <a href="https://nuft.edu.ua/"
                        rel="external"><strong>National University of Food Techlogies</strong></a></div>
                  </li>
                  <li>
                    <div><em>1<sup>st</sup> September 2004 &ndash; 30<sup>st</sup> May 2011</em></div>
                    <div><strong>Certificate of graduation</strong> at <strong>№6 Middle School of General Education in
                        Bila Tserkva</strong></div>
                  </li>
                </ul>
              </section>
            </div>
`
