### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by KozakevichVitaliy** [KozakevichVitaliy/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by FakeAccount-bsa** [comment]
`
<h3>Experience</h3>
              <h6>Recent</h6>
              <div class="highlighted">
                <p><em>14<sup>th</sup> January 2019 – present</em></p>
                <p><strong>QA Engineer</strong> at <strong><a href="https://jbwsoft.com/" rel="external">JBW
                      Soft</a></strong><br></p>
                <ul>
                  <li class="details">
                    <input type="checkbox" id="project-2">
                    <label for="project-2" class="summary">manual testing web sites and web aplication, regression
                      testing, stress testing, automated testing</label>
                    <div class="labels">
                      <div class="label">Redmine</div>
                      <div class="label">Google Developers Tools</div>
                      <div class="label">HTTP protocol</div>
                      <div class="label">HTML</div>
                      <div class="label">CSS</div>
                      <div class="label">JavaScript</div>
                      <div class="label">Java</div>
                      <div class="label">JMeter</div>
                      <div class="label">Selenium WebDriver</div>
                    </div>
                  </li>
                  <li>working with documentation, support and development of testing processes on the projects</li>
                </ul>
              </div>
              <h6>Back then</h6>
              <ul class="timeline">
                <li>
                  <p><em>15<sup>st</sup> June 2018 &ndash; 11<sup>st</sup> November 2018</em></p>
                  <p>Cook at <strong><a href="https://www.facebook.com/holybrgr/" rel="external">Holy
                        Burger</a></strong></p>
                </li>
                <li>
                  <p><em>28<sup>st</sup> October 2016 &ndash; 24<sup>st</sup> April 2018</em></p>
                  <p>Regular service in the<strong><a href="http://www.mil.gov.ua/ministry" rel="external"> Armed forces
                        of Ukraine</a></strong></p>
                </li>
                <li>
                  <p><em>Some time in August 2018</em></p>
                  <p>Listen to the music and had cool time at<strong><a href="https://zaxidfest.com/" rel="external">
                        ZAXIDFEST</a></strong></p>
                </li>
                <li>
                  <p><em>Some time in November 2015</em></p>
                  <p>Bought electric guitar<strong> Squire by Fender</strong><button id="guitar" class="audio"><svg
                        class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                        <path
                          d="M576 256c0 100.586-53.229 189.576-134.123 239.04-7.532 4.606-17.385 2.241-21.997-5.304-4.609-7.539-2.235-17.388 5.304-21.997C496.549 424.101 544 345.467 544 256c0-89.468-47.452-168.101-118.816-211.739-7.539-4.609-9.913-14.458-5.304-21.997 4.608-7.539 14.456-9.914 21.997-5.304C522.77 66.424 576 155.413 576 256zm-96 0c0-66.099-34.976-124.572-88.133-157.079-7.538-4.611-17.388-2.235-21.997 5.302-4.61 7.539-2.236 17.388 5.302 21.998C418.902 152.963 448 201.134 448 256c0 54.872-29.103 103.04-72.828 129.779-7.538 4.61-9.912 14.459-5.302 21.998 4.611 7.541 14.462 9.911 21.997 5.302C445.024 380.572 480 322.099 480 256zm-138.14-75.117c-7.538-4.615-17.388-2.239-21.998 5.297-4.612 7.537-2.241 17.387 5.297 21.998C341.966 218.462 352 236.34 352 256s-10.034 37.538-26.841 47.822c-7.538 4.611-9.909 14.461-5.297 21.998 4.611 7.538 14.463 9.909 21.998 5.297C368.247 314.972 384 286.891 384 256s-15.753-58.972-42.14-75.117zM256 88.017v335.964c0 21.436-25.942 31.999-40.971 16.971L126.059 352H24c-13.255 0-24-10.745-24-24V184c0-13.255 10.745-24 24-24h102.059l88.971-88.954C230.037 56.038 256 66.551 256 88.017zm-32 19.311l-77.659 77.644A24.001 24.001 0 0 1 129.372 192H32v128h97.372a24.001 24.001 0 0 1 16.969 7.028L224 404.67V107.328z" />
                      </svg> guitar sound
                      <audio preload="none">
                        <source src="./assets/sounds/Guitar.mp3" type="audio/mpeg">
                      </audio>
                    </button></p>
                </li>
                <li>
                  <p><em>15<sup>th</sup> August 2004</em></p>
                  <p>Relocated to <strong><a
                        href="https://www.google.com/maps/place/%D0%91%D1%96%D0%BB%D0%B0+%D0%A6%D0%B5%D1%80%D0%BA%D0%B2%D0%B0,+%D0%9A%D0%B8%D1%97%D0%B2%D1%81%D1%8C%D0%BA%D0%B0+%D0%BE%D0%B1%D0%BB.,+09100/@49.8056147,30.0519455,12z/data=!3m1!4b1!4m5!3m4!1s0x40d3423e37227b9d:0x84e311f8582cc6e8!8m2!3d49.7967977!4d30.1310853?hl=uk"
                        rel="external">Bila Tserkva</a></strong></p>
                </li>
                <li>
                  <p><em>8<sup>th</sup> February 1994</em></p>
                  <p>Born in<strong><a
                        href="https://www.google.com/maps/place/%D0%A0%D1%96%D0%B2%D0%BD%D0%B5,+%D0%A0%D1%96%D0%B2%D0%BD%D0%B5%D0%BD%D1%81%D1%8C%D0%BA%D0%B0+%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C/@50.6111564,26.1745432,12z/data=!3m1!4b1!4m5!3m4!1s0x472f6caa2d7c89d7:0x27481abdbc4e484!8m2!3d50.6199!4d26.251617?hl=uk"
                        rel="external"> Rivne, Ukraine</a></strong></p>
                </li>
              </ul>
`
